### PR TITLE
Try to fix Windows build

### PR DESCRIPTION
**Pull request by AenBleidd**
Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Comment by AenBleidd** [comment]
Hm, looks like I have no permissions to write to your repo and doing a PR to PR doesn't trigger CI.
@ChristianBeer, could you please give me necessary permissions? Thanks in advance
image

**Comment by AenBleidd** [comment]
Aha, but it runs on my repo, so everything is fine.
@ChristianBeer, could you please review and merge?

**Comment by ChristianBeer** [comment]
You have to accept my invitation. You are still shown as invited and need to respond.

**Comment by AenBleidd** [comment]
Hm, sorry, I missed the invitation somehow.

**Pull request merged**
